---
name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        id: patch
        with:
          release: v1.2.0
          level: patch
      - uses: ./
        id: minor
        with:
          release: v1.3.1
          level: minor
      - uses: ./
        id: major
        with:
          release: v1.3.1
          level: major
      - uses: ./
        id: default
        with:
          default-release: v1.3.1
          level: default
      - name: results
        run: |
          echo ${{ steps.patch.outputs.release }}
          if test "${{ steps.patch.outputs.release }}" != "v1.2.1"; then
            echo ::error::patch ${{ steps.patch.outputs.release }}
            exit 1
          fi
          if test "${{ steps.minor.outputs.release }}" != "v1.4.0"; then
            echo ::error::minor ${{ steps.minor.outputs.release }}
            exit 1
          fi
          if test "${{ steps.major.outputs.release }}" != "v2.0.0"; then
            echo ::error::major ${{ steps.major.outputs.release }}
            exit 1
          fi
          if test "${{ steps.default.outputs.release }}" != "v1.2.1"; then
            echo ::error::default ${{ steps.default.outputs.release }}
            exit 1
          fi